# Generated by Django 5.2.7 on 2026-01-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('exotico', 'Exótico'), ('otro', 'Otro')], default='perro', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(default='Juanito', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default='Quiltro', max_length=50),
            preserve_default=False,
        ),
    ]
